### ISSUE TITLE
Migrating pull requests from axnsan12/drf-yasg

### ISSUE THREAD

**Issue by JoelLefkowitz** [JoelLefkowitz/drf-yasg#1]
A number of important pull requests on axnsan12/drf-yasg were never merged into the master. I have already merged #625, #636, #644, #445 into the new release branch but quite a few of them should still be brought over.

**Comment by JoelLefkowitz** [comment]
This has actually been completed satisfactorily with axnsan12#625, axnsan12#636, axnsan12#644, axnsan12#445

**Comment by johnthagen** [comment]
It seems axnsan12#445 got lost at some point, so I opened #77 to restore it.
