### ISSUE TITLE
Remove Python 2.7 compatibility code

### ISSUE THREAD

**Issue by johnthagen** [JoelLefkowitz/drf-yasg#16]
https://github.com/JoelLefkowitz/drf-yasg/commit/8aa255cf56978046c05ea8268984cdf82d0e7d38 dropped Python 2.7 tests.

#14 dropped Python 2.7 documented support.

There are still some instances where Python 2.7 compatibility shims exist that should be removed after an initial release of `drf-yasg2`.

https://github.com/JoelLefkowitz/drf-yasg/blob/b6f5cbb95feda74d7a32adb3babe0ee507ac6bc7/src/drf_yasg/inspectors/base.py#L29

https://github.com/JoelLefkowitz/drf-yasg/blob/f630d98283cfbcf91bf3a06fb7324696a4e7d8f6/src/drf_yasg2/management/commands/generate_swagger.py#L159

https://github.com/JoelLefkowitz/drf-yasg/blob/b6f5cbb95feda74d7a32adb3babe0ee507ac6bc7/requirements/base.txt#L5

**Comment by JoelLefkowitz** [comment]
Totally agree, I'd like to have 1.18 be compatible with python 2.7 and from  release 1.19 we'll go with 3.6 - 3.9

**Comment by johnthagen** [comment]
@JoelLefkowitz That sounds great to me.

**Comment by JoelLefkowitz** [comment]
Python 2.7 support is removed in #54. At this time I have not yet changed the _insert_extras__ method from openapi.py because it is functional.
