### ISSUE TITLE
Bad Git merge pushed to release-1.18 branch

### ISSUE THREAD

**Issue by johnthagen** [JoelLefkowitz/drf-yasg#23]
Just an FYI:

https://github.com/JoelLefkowitz/drf-yasg/blob/66f4075904b88b27c151d74db3d2d2bdd3227997/src/drf_yasg2/compat.py#L111-L119

This causes lint errors due to the syntax errors.

Introduced in #22

**Comment by JoelLefkowitz** [comment]
> Just an FYI:
> 
> https://github.com/JoelLefkowitz/drf-yasg/blob/66f4075904b88b27c151d74db3d2d2bdd3227997/src/drf_yasg2/compat.py#L111-L119
> 
> This causes lint errors due to the syntax errors.
> 
> Introduced in #22

Fixed #26
