### ISSUE TITLE
Heroku app

### ISSUE THREAD

**Issue by JoelLefkowitz** [JoelLefkowitz/drf-yasg#24]
The live demo for drf_yasg2 should be deployed to heroku

**Comment by johnthagen** [comment]
Relates to #4. Currently the link in the README points to: https://drf-yasg2-demo.herokuapp.com/

**Comment by JoelLefkowitz** [comment]
Integration complete

**Comment by johnthagen** [comment]
@JoelLefkowitz Should this work now? https://drf-yasg2-demo.herokuapp.com I still see page doesn't exist.

**Comment by johnthagen** [comment]
@JoelLefkowitz Could we reopen this issue? The live demo is still not up: https://drf_yasg2-demo.herokuapp.com/ or https://drf-yasg2-demo.herokuapp.com/

**Comment by JoelLefkowitz** [comment]
Fixed in #64
