### ISSUE TITLE
Typo in package name?

### ISSUE THREAD

**Issue by maiksprenger** [JoelLefkowitz/drf-yasg#31]
Hi @JoelLefkowitz, thanks for all the work with your fork! Just to let you know, I think there's a typo in the PyPi package? 

https://pypi.org/project/dry-yasg2/ (`dry` instead of `drf`).

**Comment by JoelLefkowitz** [comment]
Fixing now

**Comment by JoelLefkowitz** [comment]
Fixed

**Comment by maiksprenger** [comment]
Thank you!
