### ISSUE TITLE
Should PyPI upload logic run on master branch?

### ISSUE THREAD

**Issue by johnthagen** [JoelLefkowitz/drf-yasg#38]
https://travis-ci.com/github/JoelLefkowitz/drf-yasg/jobs/398272466

It seems like the upload commands should only get run for tags or when manually specified. I could be missing something about the purpose of this running in `master` though.

**Comment by JoelLefkowitz** [comment]
It's to prevent publishing a commit that got pushed to branch that had local tags that got pushed. I'll remove it for 1.19 for simplicity

**Comment by JoelLefkowitz** [comment]
This is now implemented in 1.19 release
