### ISSUE TITLE
installation conflict

### ISSUE THREAD

**Issue by dadokkio** [JoelLefkowitz/drf-yasg#40]
Hello, I was using your "basename support" commit in requirements and I've just discovered that a new lib has been relesed.

Trying to move from your commit` -e git+https://github.com/JoelLefkowitz/drf-yasg.git@84a129c62bb0217b12ae7ca79c32aa2c4354e115#egg=drf-yasg drf-yasg`
 to the lib `drf-yasg2==1.18.5` I'm having issues:

```
Attempting uninstall: ruamel.yaml
    Found existing installation: ruamel-yaml 0.15.87
ERROR: Cannot uninstall 'ruamel-yaml'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

I'm not sure which package has installed ruamel-yaml,  my actual requirements.txt "drf related" is:

```
# Django Rest Framework
# ------------------------------------------------------------------------------
# https://github.com/encode/django-rest-framework
djangorestframework==3.12.1
# https://github.com/adamchainz/django-cors-headers
django-cors-headers==3.5.0
# https://github.com/alanjds/drf-nested-routers PULL
# drf-nested-routers==0.91
-e git+https://github.com/Frankkkkk/drf-nested-routers.git@a3bb6be19d8444431df7e9c0785d56f36c99c8ab#egg=drf-nested-routers
# https://github.com/JoelLefkowitz/drf-yasg FORK
drf-yasg2==1.18.5
```

Do you have any suggestion on which package I need to check or how to resolve the issue?

**Comment by johnthagen** [comment]
`ruamel.yaml` is a requirement of `drf-yasg2`:

https://github.com/JoelLefkowitz/drf-yasg/blob/32d7a63c1d7ca7d1904871550a71fb3bac38a6cf/setup.py#L19

But as you can see, it requires a newer version that what was installed into your (virtual) environment. Try again with a clean virtual environment. It's likely an issue with the old `ruamel.yaml` you had installed. Modern packages shouldn't be using `distutils` anymore, so hopefully  getting rid of that old version fixes the issue.

```bash
$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ pip install ...
```

**Comment by dadokkio** [comment]
the image should be clean since is a docker one, but I think that the issue could be related to my base image.
I'm using `FROM continuumio/miniconda3:4.8.2` as base image and it seems to be related to similar issue with pip.
I'll try to create a dockerfile to test it out.

**Comment by JoelLefkowitz** [comment]
> the image should be clean since is a docker one, but I think that the issue could be related to my base image.
> I'm using `FROM continuumio/miniconda3:4.8.2` as base image and it seems to be related to similar issue with pip.
> I'll try to create a dockerfile to test it out.

I'm closing this issue for now. Please reopen an issue if your dockerfile test fails
