### ISSUE TITLE
Missing "validation" extras_requires

### ISSUE THREAD

**Issue by johnthagen** [JoelLefkowitz/drf-yasg#41]
`drf-yasg` can be installed like:

```bash
$ pip install drf-yasg[validation]
```

- https://github.com/axnsan12/drf-yasg/blob/9ccf24c27ad46db4f566170553d49d687b6d21d6/setup.py#L43
- https://github.com/axnsan12/drf-yasg/blob/master/requirements/validation.txt

It looks like this was lost in the #28 refactoring of `setup.py`.

**Comment by JoelLefkowitz** [comment]
I had some issues with python2.7 compatibility and the validation dependencies. I think it's best to include the validation by default going forward.
