### ISSUE TITLE
Cant install from pypi

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [JoelLefkowitz/drf-yasg#5]
Hi
Package is non discoverable on pypi. Only way i managed to install it is:

**pipenv install -e git+https://github.com/JoelLefkowitz/drf-yasg#egg=drf-yasg2**

**Comment by JoelLefkowitz** [comment]
The first pypi release will be 1.18 and should be uploaded by travis given #2 is completed

**Comment by JoelLefkowitz** [comment]
Package is now available on pypi
