### ISSUE TITLE
Why does the import change?

### ISSUE THREAD

**Issue by Siecje** [JoelLefkowitz/drf-yasg#50]
I should be able to import `drf_yasg`.

**Comment by johnthagen** [comment]
I presume this is to remove the dissonance between `pip install drf-yasg2`, the package name, and the imports it provides (drf_yasg2).

I am sympathetic to the burden of to having to change a bunch of imports to move to this fork, but I personally think long term it's clearer to have the imports match the package name.

**Comment by JoelLefkowitz** [comment]
As @johnthagen said, we're sticking to a matching name

**Comment by Siecje** [comment]
This is a temporary fork until drf-yasg is updated.

**Comment by johnthagen** [comment]
@Siecje It may not be temporary if the original maintainer decides to not ever maintain `drf-yasg` or simply wants to pass it off to this fork permanently.
