### ISSUE TITLE
ModuleNotFoundError: No module named 'drf_yasg2'

### ISSUE THREAD

**Issue by mkopr** [JoelLefkowitz/drf-yasg#6]
Hi, 

I have an issue with running a Django app. 
Package installed with command: `pip install -e git+https://github.com/JoelLefkowitz/drf-yasg#egg=drf-yasg2`
I can't run django with this app in INSTALLED_APPS.
I tried with `drf_yasg2` and `drf_yasg` in installed apps section with no success.

error log:

>  $ python manage.py runserver
> 
> 2020-10-08 09:18:03,876 [INFO]- Watching for file changes with StatReloader
> Exception in thread django-main-thread:
> Traceback (most recent call last):
>   File "/home/mkopr/.pyenv/versions/3.8.1/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/home/mkopr/.pyenv/versions/3.8.1/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/mkopr/code/boilerplate/drf/env/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
>     fn(*args, **kwargs)
>   File "/home/mkopr/code/boilerplate/drf/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
>     autoreload.raise_last_exception()
>   File "/home/mkopr/code/boilerplate/drf/env/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
>     raise _exception[1]
>   File "/home/mkopr/code/boilerplate/drf/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
>     autoreload.check_errors(django.setup)()
>   File "/home/mkopr/code/boilerplate/drf/env/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
>     fn(*args, **kwargs)
>   File "/home/mkopr/code/boilerplate/drf/env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/home/mkopr/code/boilerplate/drf/env/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
>     app_config = AppConfig.create(entry)
>   File "/home/mkopr/code/boilerplate/drf/env/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
>     module = import_module(entry)
>   File "/home/mkopr/.pyenv/versions/3.8.1/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'drf_yasg2'
> 

installed packages:

>  $ pip list
> Package                Version              Location                                                 
> ---------------------- -------------------- ---------------------------------------------------------
> asgiref                3.2.10               
> certifi                2020.6.20            
> chardet                3.0.4                
> coreapi                2.3.3                
> coreschema             0.0.4                
> Django                 3.1.2                
> django-extensions      3.0.9                
> django-filter          2.4.0                
> django-request-logging 0.7.2                
> djangorestframework    3.12.1               
> drf-yasg2              1.17.2.dev3+gb6f5cbb /home/mkopr/code/boilerplate/drf/env/src/drf-yasg2/src
> flake8                 3.8.4                
> idna                   2.10                 
> inflection             0.5.1                
> isort                  5.6.0                
> itypes                 1.2.0                
> Jinja2                 2.11.2               
> MarkupSafe             1.1.1                
> mccabe                 0.6.1                
> packaging              20.4                 
> pip                    19.2.3               
> pycodestyle            2.6.0                
> pyflakes               2.2.0                
> pyparsing              2.4.7                
> pytz                   2020.1               
> requests               2.24.0               
> ruamel.yaml            0.16.12              
> ruamel.yaml.clib       0.2.2                
> setuptools             41.2.0               
> six                    1.15.0               
> sqlparse               0.4.1                
> uritemplate            3.0.1                
> urllib3                1.25.10   
>

**Comment by marcosox** [comment]
I am using `-e git+https://github.com/JoelLefkowitz/drf-yasg#egg=drf-yasg2` in my `requirements.txt`, and `drf-yasg` in `settings.py` and it works for me.

**Comment by marcosox** [comment]
After today's updates I am facing this error too (`ModuleNotFoundError: No module named 'drf_yasg2'`) .@JoelLefkowitz Can this be reopened? It happens both using the PyPi package and building from git.

@mkopr I see you closed the issue, did you solve it? If so, how?

**Comment by mkopr** [comment]
I have not solved this problem, I assume that this is the problem where docker installs the git package.

**Comment by JoelLefkowitz** [comment]
This was caused by a bad setup.py configuration not properly packaging the contents, it's been patched now for 1.18.5+

**Comment by JoelLefkowitz** [comment]
Please try installing the latest version of the package and report if there are any issues

**Comment by mkopr** [comment]
Thanks, now works fine
