### ISSUE TITLE
Update GitHub docs link

### ISSUE THREAD

**Issue by johnthagen** [JoelLefkowitz/drf-yasg#67]
For consistency, could we update the GitHub docs link to use the canocial package name:

<img width="344" alt="Screen Shot 2020-10-19 at 7 32 51 AM" src="https://user-images.githubusercontent.com/10340167/96445090-536c8e80-11dd-11eb-919d-7415b2490ea6.png">

Updated name: https://drf-yasg2.readthedocs.io/en/stable/

This is what a user is redirected to eventually and might help reduce a small amount of confusion.

**Comment by JoelLefkowitz** [comment]
Done
