### ISSUE TITLE
redoc scroll issue

### ISSUE THREAD

**Issue by junshoong** [JoelLefkowitz/drf-yasg#71]
related issue
- https://github.com/axnsan12/drf-yasg/pull/543
- https://github.com/axnsan12/drf-yasg/issues/548
- https://github.com/Redocly/redoc/issues/1167

i seem to `package.json` is fixed version, but static directory isn't.
please update static file
`static/drf_yasg2/redoc/redoc.min.js`

**Comment by garanews** [comment]
I confirm, have wrong behavior in chrome and ok in firefox.

**Comment by johnthagen** [comment]
This should be fixed in #69. If you point `pip` at this branch, you should be able to test it out on your project: https://github.com/johnthagen/drf-yasg/tree/update-js-deps

**Comment by johnthagen** [comment]
@JoelLefkowitz Could we release a 1.19.3 that includes #69 so that users can take get this fix in their projects?

**Comment by johnthagen** [comment]
@junshoong @garanews Please try the [1.19.3 release.](https://pypi.org/project/drf-yasg2/1.19.3/)

**Comment by johnthagen** [comment]
1.19.3 solved this issue for me.
