### ISSUE TITLE
Add notice that the original drf-yasg is now maintained again

### ISSUE THREAD

**Issue by johnthagen** [JoelLefkowitz/drf-yasg#80]
We should probably add a notice to the README once `drf-yasg` is fully up and running again to point people back to it.

@JoelLefkowitz Could you leave a comment here if/when you are made a maintainer of `drf-yasg`?

**Comment by JoelLefkowitz** [comment]
Am a maintainer now

**Comment by JoelLefkowitz** [comment]
Im going add a notice to our readme now
