### ISSUE TITLE
Wrong link to original project in README

### ISSUE THREAD

**Issue by maiksprenger** [JoelLefkowitz/drf-yasg#84]
Hi @JoelLefkowitz , thanks for your time you took with this fork! 

I just wanted to mention that the link back to the original project in the README actually links to this project. That had me confused ;) Here's the commit: https://github.com/JoelLefkowitz/drf-yasg/commit/f0c4d19e2be58abd191cd97ce7e1fb4c799b8fb5

If I'm not mistaken, the link should be to https://github.com/axnsan12/drf-yasg

Thanks!

**Comment by JoelLefkowitz** [comment]
Thanks for the heads up @maikhoepfel, fixed in #85.
